# Generated by Django 5.0.7 on 2024-07-28 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivariety',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 28, 16, 27, 55, 144601, tzinfo=datetime.timezone.utc)),
        ),
    ]
