# Generated by Django 5.0.7 on 2024-07-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_alter_chaivariety_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivariety',
            name='date_added',
            field=models.DateField(),
        ),
    ]
