# Generated by Django 5.0.7 on 2024-07-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_alter_chaivariety_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
